modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="simplelife"
version="1.0.0"
displayName="SimpleLife"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/sperly/SimpleLife"
authors="sperly, MCreator"

[[dependencies.simplelife]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




